version: "3"
services:
  chrome:
    image: selenium/standalone-chrome:3.141.59-xenon
    ports:
      - 4444:4444
      - 5900:5900
    shm_size: "2gb"

  fe-server:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - 80:80
